/*
 * GENERATED FILE -- source: schema/ssi_config_abi.json
 *
 * Regenerate with: python tools/gen_ssi_abi.py
 */
#ifndef SSI_CONFIG_ABI_H_
#define SSI_CONFIG_ABI_H_

#include <stdint.h>

#define SSI_CONFIG_ABI_VERSION                 (1U)
#define SSI_CONFIG_SIZE                         (256U)
#define SSI_PAUSE_INNER_ITERS                  (250U)
#define SSI_NO_ERROR_FIELD                     (0xFFFFU)
#define SSI_IEPCLK_OCP_EN                      (1U)
#define SSI_IEP_TICK_HZ                         (300000000U)

#define SSI_PRODUCER_SAMPLE_Q_FRACTION_BITS (32U)
#define SSI_DEFAULT_PRODUCER_PERIOD_IEP_TICKS (288U)
#define SSI_DEFAULT_PRODUCER_SAMPLE_AGE_LIMIT_IEP_TICKS (576U)
#define SSI_DEFAULT_PRODUCER_PREDICTION_HORIZON_LIMIT_IEP_TICKS (6000U)

#define SSI_CONFIG_OFF_ABI_VERSION                    (0x00U)
#define SSI_CONFIG_OFF_STRUCT_SIZE                    (0x04U)
#define SSI_CONFIG_OFF_REQUESTED_GENERATION           (0x08U)
#define SSI_CONFIG_OFF_PRU0_ACK_GENERATION            (0x0CU)
#define SSI_CONFIG_OFF_PRU1_ACK_GENERATION            (0x10U)
#define SSI_CONFIG_OFF_TOPOLOGY                       (0x14U)
#define SSI_CONFIG_OFF_ENCODING_TYPE                  (0x15U)
#define SSI_CONFIG_OFF_ALIGNMENT                      (0x16U)
#define SSI_CONFIG_OFF_FORMATION_MODE                 (0x17U)
#define SSI_CONFIG_OFF_FRAME_WIDTH_BITS               (0x18U)
#define SSI_CONFIG_OFF_POSITION_OFFSET_BITS           (0x1AU)
#define SSI_CONFIG_OFF_POSITION_WIDTH_BITS            (0x1CU)
#define SSI_CONFIG_OFF_SINGLETURN_WIDTH_BITS          (0x1EU)
#define SSI_CONFIG_OFF_MULTITURN_WIDTH_BITS           (0x20U)
#define SSI_CONFIG_OFF_ERROR_OFFSET_BITS              (0x22U)
#define SSI_CONFIG_OFF_ERROR_WIDTH_BITS               (0x24U)
#define SSI_CONFIG_OFF_PADDING_WIDTH_BITS             (0x26U)
#define SSI_CONFIG_OFF_CLOCK_HIGH_CYCLES              (0x28U)
#define SSI_CONFIG_OFF_CLOCK_LOW_CYCLES               (0x2CU)
#define SSI_CONFIG_OFF_SAMPLE_DELAY_CYCLES            (0x30U)
#define SSI_CONFIG_OFF_TV_CYCLES                      (0x34U)
#define SSI_CONFIG_OFF_TM_PAUSE_OUTER_ITERS           (0x38U)
#define SSI_CONFIG_OFF_TP_PAUSE_OUTER_ITERS           (0x3CU)
#define SSI_CONFIG_OFF_FORMATION_PAUSE_OUTER_ITERS    (0x40U)
#define SSI_CONFIG_OFF_SEQUENCE_HOLD_MODE             (0x44U)
#define SSI_CONFIG_OFF_FAULT_MODE                     (0x45U)
#define SSI_CONFIG_OFF_CAPTURE_MODE                   (0x46U)
#define SSI_CONFIG_OFF_PRODUCER_MODE                  (0x47U)
#define SSI_CONFIG_OFF_SEQUENCE_HOLD_COUNT            (0x48U)
#define SSI_CONFIG_OFF_FAULT_ARGUMENT                 (0x4CU)
#define SSI_CONFIG_OFF_FAULT_REPEAT_COUNT             (0x50U)
#define SSI_CONFIG_OFF_PRODUCER_PERIOD_IEP_TICKS      (0x54U)
#define SSI_CONFIG_OFF_PRODUCER_SAMPLE_AGE_LIMIT_IEP_TICKS (0x58U)
#define SSI_CONFIG_OFF_PRODUCER_PREDICTION_HORIZON_LIMIT_IEP_TICKS (0x5CU)

#define SSI_FRAMES_OFF                                (0x0100U)
#define SSI_FRAME_SLOT_COUNT                          (16U)
#define SSI_FRAME_SLOT_SIZE                           (16U)
#define SSI_FRAME_SLOT_OFF_FRAME_BITS                 (0x00U)
#define SSI_FRAME_SLOT_OFF_HOLD_OVERRIDE_CYCLES_OR_FRAMES (0x08U)

#define SSI_MAILBOX_OFF                               (0x0200U)
#define SSI_MAILBOX_OFF_SEQ                           (0x00U)
#define SSI_MAILBOX_OFF_RAW_FRAME                     (0x04U)
#define SSI_MAILBOX_OFF_POSITION_VALUE                (0x0CU)
#define SSI_MAILBOX_OFF_STATUS_BITS                   (0x10U)
#define SSI_MAILBOX_OFF_FRAME_COUNTER                 (0x14U)
#define SSI_MAILBOX_OFF_TIMESTAMP_CYCLES              (0x18U)

#define SSI_CAPTURE_OFF                               (0x0240U)
#define SSI_CAPTURE_OFF_TRACE_WRITE_INDEX             (0x00U)
#define SSI_CAPTURE_OFF_TRACE_OVERRUN_COUNT           (0x04U)

#define SSI_TRACE_OFF                                 (0x0400U)
#define SSI_TRACE_RECORD_COUNT                        (1024U)
#define SSI_TRACE_RECORD_SIZE                         (24U)
#define SSI_TRACE_RECORD_TIMESTAMP_CYCLES_OFF         (0x00U)
#define SSI_TRACE_RECORD_RAW_FRAME_OFF                (0x08U)
#define SSI_TRACE_RECORD_POSITION_VALUE_OFF           (0x10U)
#define SSI_TRACE_RECORD_STATUS_BITS_OFF              (0x14U)
#define SSI_TRACE_RECORD_FLAGS_OFF                    (0x16U)

#define SSI_PRODUCER_SAMPLES_OFF                      (0x6400U)
#define SSI_PRODUCER_SAMPLE_COUNT                     (256U)
#define SSI_PRODUCER_SAMPLE_SIZE                      (32U)
#define SSI_PRODUCER_SAMPLE_OFF_WRITE_SEQ             (0x00U)
#define SSI_PRODUCER_SAMPLE_OFF_TIMESTAMP_IEP         (0x08U)
#define SSI_PRODUCER_SAMPLE_OFF_POSITION_Q31_32       (0x10U)
#define SSI_PRODUCER_SAMPLE_OFF_GENERATION            (0x18U)
#define SSI_PRODUCER_SAMPLE_OFF_FLAGS                 (0x1CU)

#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF           (0x8400U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_SIZE          (64U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_LATEST_WRITE_SEQ (0x00U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_ACCEPTED_COUNT (0x08U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_COHERENCE_RETRY_COUNT (0x0CU)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_STALE_SAMPLE_COUNT (0x10U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_RING_OVERRUN_COUNT (0x14U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_LAST_REQUEST_TIMESTAMP_IEP (0x18U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_LAST_ESTIMATE_POSITION_Q31_32 (0x20U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_STATUS    (0x28U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_GENERATION (0x2CU)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_HEAD_SEQ  (0x30U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_LATEST_SLOT_INDEX (0x34U)
#define SSI_PRODUCER_SAMPLE_DIAGNOSTICS_OFF_LATEST_STABLE_SAMPLE_SEQ (0x38U)

#define SSI_CONFIG_OFF_FORMATION_PAUSE_ITERS SSI_CONFIG_OFF_FORMATION_PAUSE_OUTER_ITERS
#define SSI_FRAME_SLOT_OFF_HOLD_OVERRIDE SSI_FRAME_SLOT_OFF_HOLD_OVERRIDE_CYCLES_OR_FRAMES

enum {
    SSI_TOPOLOGY_LOOPBACK = 0,
    SSI_TOPOLOGY_READER_ONLY = 1,
};

enum {
    SSI_ENCODING_BINARY = 0,
    SSI_ENCODING_GRAY = 1,
    SSI_ENCODING_GRAY_EXCESS = 2,
    SSI_ENCODING_TANNENBAUM = 3,
};

enum {
    SSI_FORMATION_ASYNCHRONOUS = 0,
    SSI_FORMATION_SYNCHRONOUS = 1,
};

enum {
    SSI_HOLD_FRAMES = 0,
    SSI_HOLD_TIME = 1,
};

enum {
    SSI_PRODUCER_MODE_STATIC_SEQUENCE = 0,
    SSI_PRODUCER_MODE_TIMESTAMPED = 1,
};

enum {
    SSI_PRODUCER_SAMPLE_FLAG_VALID = 1,
};

enum {
    SSI_FAULT_NONE = 0,
    SSI_FAULT_STATUS_BITS = 1,
    SSI_FAULT_SENTINEL = 2,
    SSI_FAULT_ALL_ONES = 3,
    SSI_FAULT_MISSING_RESPONSE = 4,
    SSI_FAULT_SHORT_FRAME = 5,
    SSI_FAULT_EXCESSIVE_TV = 6,
    SSI_FAULT_STUCK_LOW = 7,
    SSI_FAULT_STUCK_HIGH = 8,
};

#endif /* SSI_CONFIG_ABI_H_ */
